import test from 'node:test';
import assert from 'node:assert/strict';
import botHandler, { callLlm, commandReply, createGitHubIssue, validateProviderUrl } from '../api/bot.mjs';
import healthHandler, { healthPayload } from '../api/health.mjs';

function createResponse(){const result={statusCode:200,headers:{},body:undefined};return{setHeader(n,v){result.headers[n.toLowerCase()]=v;},status(c){result.statusCode=c;return this;},json(p){result.body=p;return result;},result};}
async function invoke(handler,{method='POST',body={},headers={}}={}){const response=createResponse();await handler({method,body,headers},response);return response.result;}
async function withEnv(values,callback){const previous={};for(const[k,v]of Object.entries(values)){previous[k]=process.env[k];if(v===undefined)delete process.env[k];else process.env[k]=v;}try{return await callback();}finally{for(const[k,v]of Object.entries(previous)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}}

test('proxy status reports strategic and operational review line',async()=>{const r=await invoke(botHandler,{body:{message:'/status'}});assert.equal(r.statusCode,200);assert.match(r.body.reply,/Parent-Gate: LR5/);assert.match(r.body.reply,/Issue #82/);assert.match(r.body.reply,/LR5\.1/);assert.match(r.body.reply,/Issue #88/);assert.match(r.body.reply,/Assetscan #123/);assert.match(r.body.reply,/6\.215 Dateien/);assert.match(r.body.reply,/Issue #153/);assert.match(r.body.reply,/Issue #155/);assert.match(r.body.reply,/0\/1/);assert.match(r.body.reply,/Bildgenerierung.*gesperrt/);assert.match(r.body.reply,/0\/4/);assert.match(r.body.reply,/0\/3/);assert.doesNotMatch(r.body.reply,/100 ?%/);});
test('proxy next requires local review and human decision',()=>{const r=commandReply('/next');assert.match(r.reply,/Issue #155/);assert.match(r.reply,/lokalen M1/);assert.match(r.reply,/Contact Sheet/);assert.match(r.reply,/Issue #153/);assert.match(r.reply,/keine Bild-, GPU-, Provider-, Modell- oder LoRA-Ausführung/i);});
test('characters reflect existing assets and blocking order',()=>{const r=commandReply('/characters');assert.match(r.reply,/Pilotlinie Das Zimmer/);assert.match(r.reply,/Character-Sheets und LoRA-Trainingsbilder/);assert.match(r.reply,/0\/1/);assert.match(r.reply,/Dashboard-SVG ist kein Master/);assert.match(r.reply,/Basti, Jule, Don Miau, alle Sets und Stimmen bleiben blockiert/);assert.match(r.reply,/#155/);assert.match(r.reply,/#153/);});
test('render command is hard blocked and creates no mutation',()=>{const r=commandReply('/render shot-1');assert.match(r.reply,/RENDER BLOCKED/);assert.match(r.reply,/Issue #155/);assert.match(r.reply,/Issue #153/);assert.match(r.reply,/weder ein Render-Issue noch eine Bild-, GPU-, Provider-, Modell- oder LoRA-Ausführung/);assert.equal(r.mutation,undefined);});
test('task command retains strict comic scope and active line tracking',()=>{const r=commandReply('/task Ricco Reviewpaket prüfen');assert.match(r.mutation.body,/Issue #82/);assert.match(r.mutation.body,/Issue #88/);assert.match(r.mutation.body,/Issue #123/);assert.match(r.mutation.body,/Issue #153/);assert.match(r.mutation.body,/Issue #155/);assert.match(r.mutation.body,/project\/active-line\.json/);assert.match(r.mutation.body,/Kandidaten: 0\/1/);assert.match(r.mutation.body,/Bildgenerierung jetzt erlaubt: nein/);assert.match(r.mutation.body,/kein LoRA-Training/i);assert.match(r.mutation.body,/Pagebabe\/comic/);});
test('invalid methods and malformed bodies fail safely',async()=>{assert.equal((await invoke(botHandler,{method:'GET'})).statusCode,405);assert.equal((await invoke(botHandler,{body:'{broken'})).statusCode,400);});
test('admin protection blocks task mutations',async()=>{await withEnv({COMIC_ADMIN_KEY:'secret',GITHUB_TOKEN:undefined},async()=>{const r=await invoke(botHandler,{body:{message:'/task Test'}});assert.equal(r.statusCode,403);});});
test('blocked render does not require admin because it performs no write',async()=>{await withEnv({COMIC_ADMIN_KEY:'secret',GITHUB_TOKEN:undefined},async()=>{const r=await invoke(botHandler,{body:{message:'/render shot-1'}});assert.equal(r.statusCode,200);assert.match(r.body.reply,/RENDER BLOCKED/);});});
test('provider allowlist rejects unsafe hosts',async()=>{await withEnv({NODE_ENV:'production'},async()=>{assert.equal(validateProviderUrl('http://api.openai.com/v1'),null);assert.equal(validateProviderUrl('https://127.0.0.1/v1'),null);assert.equal(validateProviderUrl('https://evil.example/v1'),null);assert.equal(validateProviderUrl('https://integrate.api.nvidia.com/v1'),'https://integrate.api.nvidia.com/v1');});});
test('LLM receives current operational context',async()=>{let request;const reply=await callLlm({message:'Prüfe den Rettungsplan.',history:[],apiKey:'k',baseUrl:'https://integrate.api.nvidia.com/v1',model:'m',fetchImpl:async(url,options)=>{request={url,body:JSON.parse(options.body)};return{ok:true,json:async()=>({choices:[{message:{content:'ok'}}]})};}});assert.equal(reply,'ok');const system=request.body.messages[0].content;assert.match(system,/RECOVERY LINE ACTIVE/);assert.match(system,/aktives Parent-Gate: LR5 Visual-, Set- und Voice-Locks/);assert.match(system,/LR5\.1 Ricco Visual-Master-Vertrag/);assert.match(system,/Issue #88/);assert.match(system,/Issue #123/);assert.match(system,/Issue #153/);assert.match(system,/Issue #155/);assert.match(system,/project\/active-line\.json/);assert.match(system,/Pages 29154561431/);assert.match(system,/Kandidatenstand: 0\/1/);assert.match(system,/Bildgenerierung ist jetzt NICHT erlaubt/);assert.match(system,/keine aktuelle Prozentzahl/i);assert.match(system,/Kein Blind-Merge/i);});
test('GitHub writes are hard scoped to comic',async()=>{let request;const issue=await createGitHubIssue({title:'t',body:'b'},{token:'x',repository:'Pagebabe/comic',fetchImpl:async(url,options)=>{request={url,options};return{ok:true,json:async()=>({number:1})};}});assert.equal(issue.number,1);assert.equal(request.url,'https://api.github.com/repos/Pagebabe/comic/issues');await assert.rejects(()=>createGitHubIssue({title:'t'},{token:'x',repository:'Pagebabe/other'}),/ausschließlich/);});
test('health remains safe',async()=>{const p=healthPayload({COMIC_ACCESS_KEY:'x',COMIC_ADMIN_KEY:'y',LLM_API_KEY:'a',LLM_BASE_URL:'b',LLM_MODEL:'c',GITHUB_TOKEN:'d',GITHUB_REPOSITORY:'Pagebabe/comic'});assert.equal(p.status,'ok');assert.equal(JSON.stringify(p).includes('COMIC_ACCESS_KEY'),false);assert.equal((await invoke(healthHandler,{method:'GET'})).statusCode,200);});
