import test from 'node:test';
import assert from 'node:assert/strict';
import botHandler, { callLlm, commandReply, createGitHubIssue, validateProviderUrl } from '../api/bot.mjs';
import healthHandler, { healthPayload } from '../api/health.mjs';

function createResponse(){const result={statusCode:200,headers:{},body:undefined};return{setHeader(n,v){result.headers[n.toLowerCase()]=v;},status(c){result.statusCode=c;return this;},json(p){result.body=p;return result;},result};}
async function invoke(handler,{method='POST',body={},headers={}}={}){const response=createResponse();await handler({method,body,headers},response);return response.result;}
async function withEnv(values,callback){const previous={};for(const[k,v]of Object.entries(values)){previous[k]=process.env[k];if(v===undefined)delete process.env[k];else process.env[k]=v;}try{return await callback();}finally{for(const[k,v]of Object.entries(previous)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}}

test('proxy status reports closed LR4 and active LR5 without completeness percentage',async()=>{const r=await invoke(botHandler,{body:{message:'/status'}});assert.equal(r.statusCode,200);assert.match(r.body.reply,/LR5 VISUAL-, SET- UND VOICE-LOCKS/);assert.match(r.body.reply,/LR0 bis LR4 sind geschlossen/);assert.match(r.body.reply,/9\/9 Stationen/);assert.match(r.body.reply,/Das Zimmer/);assert.match(r.body.reply,/0\/4/);assert.match(r.body.reply,/0\/3/);assert.match(r.body.reply,/partiell/);assert.doesNotMatch(r.body.reply,/100 ?%/);});
test('proxy next protects first Ricco master candidate',()=>{const r=commandReply('/next');assert.match(r.reply,/Ricco-Character-Master-Kandidaten/);assert.match(r.reply,/source-bound/);assert.match(r.reply,/versionierten Kandidaten/);assert.match(r.reply,/Kein Massenrendern/);assert.match(r.reply,/keine automatische Masterfreigabe/i);assert.match(r.reply,/kein Blind-Merge/i);});
test('characters reflect selected pilot but open LR5 master gates',()=>{const r=commandReply('/characters');assert.match(r.reply,/ausgewählten Pilotlinie Das Zimmer/);assert.match(r.reply,/Visuelle Master stehen 0\/4/);assert.match(r.reply,/LR5 beginnt kontrolliert mit Ricco/);assert.match(r.reply,/sichtbare menschliche Entscheidung/);});
test('render command prepares only a review-required LR5 candidate',()=>{const r=commandReply('/render shot-1');assert.match(r.reply,/LR5-Renderkandidat/);assert.match(r.reply,/nicht ausgeführt oder freigegeben/);assert.match(r.mutation.body,/REVIEW_REQUIRED_NOT_EXECUTED/);assert.match(r.mutation.body,/keine automatische Masterfreigabe/i);assert.match(r.mutation.body,/Ausführung und Kosten bleiben separat zu genehmigen/);});
test('task command retains strict comic scope and LR5 tracking',()=>{const r=commandReply('/task Ricco Prüfvertrag definieren');assert.match(r.mutation.body,/Issue #82/);assert.match(r.mutation.body,/LR0 bis LR4: geschlossen/);assert.match(r.mutation.body,/Character-Master: 0\/4/);assert.match(r.mutation.body,/REVIEW_REQUIRED/);assert.match(r.mutation.body,/kein Growth OS/i);assert.match(r.mutation.body,/Pagebabe\/comic/);});
test('invalid methods and malformed bodies fail safely',async()=>{assert.equal((await invoke(botHandler,{method:'GET'})).statusCode,405);assert.equal((await invoke(botHandler,{body:'{broken'})).statusCode,400);});
test('admin protection blocks mutations',async()=>{await withEnv({COMIC_ADMIN_KEY:'secret',GITHUB_TOKEN:undefined},async()=>{const r=await invoke(botHandler,{body:{message:'/task Test'}});assert.equal(r.statusCode,403);});});
test('provider allowlist rejects unsafe hosts',async()=>{await withEnv({NODE_ENV:'production'},async()=>{assert.equal(validateProviderUrl('http://api.openai.com/v1'),null);assert.equal(validateProviderUrl('https://127.0.0.1/v1'),null);assert.equal(validateProviderUrl('https://evil.example/v1'),null);assert.equal(validateProviderUrl('https://integrate.api.nvidia.com/v1'),'https://integrate.api.nvidia.com/v1');});});
test('LLM receives current LR5 context',async()=>{let request;const reply=await callLlm({message:'Prüfe den Rettungsplan.',history:[],apiKey:'k',baseUrl:'https://integrate.api.nvidia.com/v1',model:'m',fetchImpl:async(url,options)=>{request={url,body:JSON.parse(options.body)};return{ok:true,json:async()=>({choices:[{message:{content:'ok'}}]})};}});assert.equal(reply,'ok');const system=request.body.messages[0].content;assert.match(system,/RECOVERY LINE ACTIVE/);assert.match(system,/aktives Gate: LR5 Visual-, Set- und Voice-Locks/);assert.match(system,/Pages 29152807415/);assert.match(system,/9\/9 Stationen/);assert.match(system,/Issue #82/);assert.match(system,/keine aktuelle Prozentzahl/i);assert.match(system,/Kein Blind-Merge/i);});
test('GitHub writes are hard scoped to comic',async()=>{let request;const issue=await createGitHubIssue({title:'t',body:'b'},{token:'x',repository:'Pagebabe/comic',fetchImpl:async(url,options)=>{request={url,options};return{ok:true,json:async()=>({number:1})};}});assert.equal(issue.number,1);assert.equal(request.url,'https://api.github.com/repos/Pagebabe/comic/issues');await assert.rejects(()=>createGitHubIssue({title:'t'},{token:'x',repository:'Pagebabe/other'}),/ausschließlich/);});
test('health remains safe',async()=>{const p=healthPayload({COMIC_ACCESS_KEY:'x',COMIC_ADMIN_KEY:'y',LLM_API_KEY:'a',LLM_BASE_URL:'b',LLM_MODEL:'c',GITHUB_TOKEN:'d',GITHUB_REPOSITORY:'Pagebabe/comic'});assert.equal(p.status,'ok');assert.equal(JSON.stringify(p).includes('COMIC_ACCESS_KEY'),false);assert.equal((await invoke(healthHandler,{method:'GET'})).statusCode,200);});
