import test from 'node:test';
import assert from 'node:assert/strict';
import { buildIssueDraft, callBrowserLlm, localCommandReply, validateBrowserProviderUrl } from '../lib/browser-director.mjs';

test('browser status reports the current truth',()=>{const r=localCommandReply('/status');assert.match(r.reply,/LINE RESET/);assert.match(r.reply,/Audit-\/Status-Shell/);assert.match(r.reply,/DECISION_REQUIRED/);assert.doesNotMatch(r.reply,/100 ?%/);});
test('browser next protects atomic rescue',()=>{const r=localCommandReply('/next');assert.match(r.reply,/Truth Reset/);assert.match(r.reply,/archive\/legacy-comic-2026-07-10/);assert.match(r.reply,/Kein.*Blind-Merge/i);});
test('browser characters remain candidate plans',()=>{const r=localCommandReply('/characters');assert.match(r.reply,/Kandidaten-Bibles/);assert.match(r.reply,/keinen endgültig autorisierten Canon-Status/);});
test('browser plan is LR0 through LR5',()=>{const r=localCommandReply('/plan');for(const marker of ['LR0','LR1','LR2','LR3','LR4','LR5'])assert.match(r.reply,new RegExp(marker));});
test('issue draft contains line reset boundaries',()=>{const url=new URL(buildIssueDraft({type:'WORK PACKET',title:'Studio retten'}));const body=url.searchParams.get('body');assert.equal(url.pathname,'/Pagebabe/comic/issues/new');assert.match(body,/Issue #36/);assert.match(body,/DECISION_REQUIRED/);assert.match(body,/kein Growth OS/i);assert.match(body,/kein Blind-Merge/i);assert.match(body,/Pagebabe\/comic/);});
test('render draft is visibly blocked',()=>{const r=localCommandReply('/render shot-1');assert.match(r.reply,/LINE RESET/);assert.match(r.issueDraftUrl,/github\.com/);});
test('provider validation stays HTTPS and allowlisted',()=>{assert.equal(validateBrowserProviderUrl('http://integrate.api.nvidia.com/v1'),null);assert.equal(validateBrowserProviderUrl('https://evil.example/v1'),null);assert.equal(validateBrowserProviderUrl('https://api.openai.com/v1'),'https://api.openai.com/v1');});
test('browser LLM receives truth context',async()=>{let captured;const reply=await callBrowserLlm({message:'Audit',history:[],apiKey:'k',baseUrl:'https://api.openai.com/v1',model:'m',fetchImpl:async(url,options)=>{captured=JSON.parse(options.body);return{ok:true,json:async()=>({choices:[{message:{content:'ok'}}]})};}});assert.equal(reply,'ok');const system=captured.messages[0].content;assert.match(system,/LINE RESET/);assert.match(system,/Das Zimmer und Der Solidarpreis/);assert.match(system,/keine aktuelle Prozentzahl/i);});
