import test from 'node:test';
import assert from 'node:assert/strict';
import { buildIssueDraft, callBrowserLlm, localCommandReply, validateBrowserProviderUrl } from '../lib/browser-director.mjs';

test('browser status reports LR0 and LR1 closed with LR2 active',()=>{const r=localCommandReply('/status');assert.match(r.reply,/LR0 Truth Reset und LR1 Pilotentscheidung sind abgeschlossen/);assert.match(r.reply,/Das Zimmer/);assert.match(r.reply,/LR2 Studio Foundation/);assert.match(r.reply,/Issue #45/);assert.match(r.reply,/Audit-\/Status-Shell/);assert.doesNotMatch(r.reply,/100 ?%/);});
test('browser next protects atomic foundation rescue',()=>{const r=localCommandReply('/next');assert.match(r.reply,/Archivbestand/);assert.match(r.reply,/Vite-\/React-Foundation/);assert.match(r.reply,/Build und Browser-Smoke-Test/);assert.match(r.reply,/Kein Blind-Merge/);assert.match(r.reply,/keine Bildgenerierung/i);});
test('browser characters reflect selected pilot but open detail gates',()=>{const r=localCommandReply('/characters');assert.match(r.reply,/ausgewählten Pilotlinie Das Zimmer/);assert.match(r.reply,/offenem Review/);assert.match(r.reply,/Visuelle Master bleiben 0\/4/);});
test('browser plan is LR0 through LR6',()=>{const r=localCommandReply('/plan');for(const marker of ['LR0','LR1','LR2','LR3','LR4','LR5','LR6'])assert.match(r.reply,new RegExp(marker));assert.match(r.reply,/Das Zimmer ausgewählt/);});
test('issue draft carries LR2 and strict scope',()=>{const url=new URL(buildIssueDraft({type:'WORK PACKET',title:'Studio Foundation inventarisieren'}));const body=url.searchParams.get('body');assert.equal(url.pathname,'/Pagebabe/comic/issues/new');assert.match(body,/Issue #45/);assert.match(body,/LR1 Pilotentscheidung: Das Zimmer ausgewählt/);assert.match(body,/Kein Growth OS/i);assert.match(body,/Kein Blind-Merge/i);assert.match(body,/Pagebabe\/comic/);});
test('render draft is visibly blocked',()=>{const r=localCommandReply('/render shot-1');assert.match(r.reply,/Produktionsapp-Rettung/);assert.match(r.reply,/Visual-Locks/);assert.match(r.issueDraftUrl,/github\.com/);});
test('provider validation stays HTTPS and allowlisted',()=>{assert.equal(validateBrowserProviderUrl('http://integrate.api.nvidia.com/v1'),null);assert.equal(validateBrowserProviderUrl('https://evil.example/v1'),null);assert.equal(validateBrowserProviderUrl('https://api.openai.com/v1'),'https://api.openai.com/v1');});
test('browser LLM receives LR2 truth context',async()=>{let captured;const reply=await callBrowserLlm({message:'Audit',history:[],apiKey:'k',baseUrl:'https://api.openai.com/v1',model:'m',fetchImpl:async(url,options)=>{captured=JSON.parse(options.body);return{ok:true,json:async()=>({choices:[{message:{content:'ok'}}]})};}});assert.equal(reply,'ok');const system=captured.messages[0].content;assert.match(system,/RECOVERY LINE ACTIVE/);assert.match(system,/aktives Gate: LR2 Studio Foundation retten/);assert.match(system,/ausgewählter Pilot: Das Zimmer/);assert.match(system,/keine aktuelle Prozentzahl/i);});
