import test from 'node:test';
import assert from 'node:assert/strict';
import { buildIssueDraft, callBrowserLlm, localCommandReply, validateBrowserProviderUrl } from '../lib/browser-director.mjs';

test('browser status reports active LR5.1 zero state',()=>{const r=localCommandReply('/status');assert.match(r.reply,/LR0 bis LR4 sind öffentlich geschlossen/);assert.match(r.reply,/LR5\.1 Ricco Visual-Master-Vertrag/);assert.match(r.reply,/Issue #88/);assert.match(r.reply,/CONTRACT_READY_REVIEW_REQUIRED/);assert.match(r.reply,/0\/1/);assert.match(r.reply,/Bildgenerierung.*gesperrt/);assert.match(r.reply,/0\/4/);assert.match(r.reply,/0\/3/);assert.doesNotMatch(r.reply,/100 ?%/);});
test('browser next requires public contract proof before one candidate',()=>{const r=localCommandReply('/next');assert.match(r.reply,/LR5\.1-Vertrag/);assert.match(r.reply,/CI, Desktop, Mobil und Pages/);assert.match(r.reply,/CONTRACT_APPROVED_FOR_ONE_CANDIDATE/);assert.match(r.reply,/genau ein Ricco-Review-Sheet/);assert.match(r.reply,/keine Bild-, GPU-, Provider- oder LoRA-Ausführung/i);});
test('browser characters preserve LR5.1 blocking order',()=>{const r=localCommandReply('/characters');assert.match(r.reply,/Pilotlinie Das Zimmer/);assert.match(r.reply,/REVIEW_REQUIRED/);assert.match(r.reply,/0\/1 Kandidat/);assert.match(r.reply,/Dashboard-SVG ist kein Master/);assert.match(r.reply,/Basti, Jule, Don Miau, Sets und Stimmen bleiben.*blockiert/);});
test('browser plan is LR0 through LR6 with LR5.1',()=>{const r=localCommandReply('/plan');for(const marker of ['LR0','LR1','LR2','LR3','LR4','LR5','LR5.1','LR6'])assert.match(r.reply,new RegExp(marker.replace('.','\\.')));assert.match(r.reply,/Ricco-Vertrag REVIEW_REQUIRED/);assert.match(r.reply,/0\/1/);assert.match(r.reply,/Ausführung gesperrt/);});
test('issue draft carries LR5.1 and strict scope',()=>{const url=new URL(buildIssueDraft({type:'LR5.1 WORK PACKET',title:'Ricco Vertrag sichtbar prüfen'}));const body=url.searchParams.get('body');assert.equal(url.pathname,'/Pagebabe/comic/issues/new');assert.match(body,/Issue #82/);assert.match(body,/Issue #88/);assert.match(body,/CONTRACT_READY_REVIEW_REQUIRED/);assert.match(body,/Kandidaten: 0\/1/);assert.match(body,/Bildgenerierung jetzt erlaubt: nein/);assert.match(body,/CONTRACT_APPROVED_FOR_ONE_CANDIDATE/);assert.match(body,/Kein LoRA-Training/i);assert.match(body,/Pagebabe\/comic/);});
test('render command is hard blocked and creates no issue draft',()=>{const r=localCommandReply('/render shot-1');assert.match(r.reply,/RENDER BLOCKED/);assert.match(r.reply,/CONTRACT_APPROVED_FOR_ONE_CANDIDATE/);assert.match(r.reply,/kein Render-Issue vorbereitet/);assert.equal(r.issueDraftUrl,undefined);});
test('provider validation stays HTTPS and allowlisted',()=>{assert.equal(validateBrowserProviderUrl('http://integrate.api.nvidia.com/v1'),null);assert.equal(validateBrowserProviderUrl('https://evil.example/v1'),null);assert.equal(validateBrowserProviderUrl('https://api.openai.com/v1'),'https://api.openai.com/v1');});
test('browser LLM receives LR5.1 truth context',async()=>{let captured;const reply=await callBrowserLlm({message:'Audit',history:[],apiKey:'k',baseUrl:'https://api.openai.com/v1',model:'m',fetchImpl:async(url,options)=>{captured=JSON.parse(options.body);return{ok:true,json:async()=>({choices:[{message:{content:'ok'}}]})};}});assert.equal(reply,'ok');const system=captured.messages[0].content;assert.match(system,/RECOVERY LINE ACTIVE/);assert.match(system,/aktives Gate: LR5 Visual-, Set- und Voice-Locks/);assert.match(system,/LR5\.1 Ricco Visual-Master-Vertrag/);assert.match(system,/Issue #88/);assert.match(system,/Pages 29154561431/);assert.match(system,/Kandidatenstand: 0\/1/);assert.match(system,/Bildgenerierung ist jetzt NICHT erlaubt/);assert.match(system,/CONTRACT_APPROVED_FOR_ONE_CANDIDATE/);assert.match(system,/keine aktuelle Prozentzahl/i);});
