import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';

const expectedCommit = '90079ccb0cd51be865c05bcb88cc22e63a287a24';
const script = new URL('../scripts/wait_public_proof_barrier.mjs', import.meta.url);
const rootBoundaries={imageGenerationAllowed:false,providerExecutionAllowed:false,creativeApprovalGranted:false,growthOsIntegrated:false,livePublishingAllowed:false};
const payloads = {
  '/proof/runtime-evidence.json': {status:'pass',commit:expectedCommit,activeGate:'LR5',activeWorkPackage:'LR5.1',route:'http://example/audit.html'},
  '/proof/root-entry/root-entry-runtime-evidence.json': {status:'pass',commit:expectedCommit,trackingIssue:121,parentIssue:117,primaryAction:'./studio/#cockpit',auditRoute:'./audit.html',riccoCandidates:0,productionReady:false,beginnerReady:false,imageGenerationAllowed:false,growthOsIntegrated:false},
  '/proof/studio/studio-runtime-evidence.json': {status:'pass',commit:expectedCommit,activeGate:'LR5',activeWorkPackage:'LR5.1'},
  '/proof/studio/academy-runtime-evidence.json': {status:'pass',commit:expectedCommit,stageCount:12,creativeApprovalGranted:false,finalEpisodeApprovalGranted:false},
  '/proof/readiness/academy-readiness-runtime-evidence.json': {status:'pass',commit:expectedCommit,readinessScore:'2/10 CLOSED_VERIFIED · 7 PARTIAL · 1 OPEN',productionReady:false,beginnerReady:false,creativeApprovalGranted:false},
  '/proof/cockpit/production-cockpit-runtime-evidence.json': {status:'pass',commit:expectedCommit,trackingIssue:117,activeGate:'LR5.1',activeWorkPackage:88,workspaceCount:6,riccoCandidates:0,imageGenerationAllowed:false,creativeApprovalGranted:false,productionReady:false,beginnerReady:false,growthOsIntegrated:false},
  '/project/production-academy-status.json': {status:'proven_guided_training_ready_novice_acceptance_open',readiness:{productionReady:false,beginnerReady:false,observedNoviceRunPassed:false}},
  '/project/production-readiness-v1.json': {status:'NOT_PRODUCTION_READY',currentScore:{display:'2/10 CLOSED_VERIFIED · 7 PARTIAL · 1 OPEN'},academyBoundary:{productionReady:false,beginnerReady:false}},
  '/project/production-cockpit-v1.json': {status:'WORKING_COCKPIT_V1',route:'/studio/#cockpit',trackingIssue:117,activeGate:{id:'LR5.1',trackingIssue:88},nextAllowedStep:{decision:'CONTRACT_APPROVED_FOR_ONE_CANDIDATE'},counts:{riccoCandidates:0},sections:[{},{},{},{},{},{}],boundaries:{imageGenerationAllowed:false,providerExecutionAllowed:false,batchAllowed:false,loraTrainingAllowed:false,automaticMasterApprovalAllowed:false,growthOsIntegrated:false,livePublishingAllowed:false,productionReady:false,beginnerReady:false}},
  '/project/root-entry-v1.json': {status:'ROOT_ENTRY_READY_FOR_PROOF',route:'/',trackingIssue:121,parentIssue:117,primaryAction:{href:'./studio/#cockpit'},legacyAudit:{preserved:true,route:'/audit.html'},currentState:{riccoCandidates:0,productionReady:false,beginnerReady:false},boundaries:rootBoundaries}
};
async function withServer(overrides,callback){const server=createServer((request,response)=>{const p=new URL(request.url,'http://localhost').pathname;const payload=overrides[p]??payloads[p];if(!payload){response.writeHead(404).end('not found');return;}response.setHeader('content-type','application/json');response.end(JSON.stringify(payload));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const address=server.address();try{await callback(`http://127.0.0.1:${address.port}/`);}finally{await new Promise((r,j)=>server.close(e=>e?j(e):r()));}}
function runBarrier(baseUrl,output){return new Promise(resolve=>{const child=spawn(process.execPath,[script.pathname,'--base-url',baseUrl,'--expect-commit',expectedCommit,'--output',output,'--attempts','2','--delay-ms','10'],{stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.on('close',code=>resolve({code,stdout,stderr}));});}
test('barrier writes all ten public contracts after a successful check',async()=>{const output=await mkdtemp(join(tmpdir(),'comic-public-barrier-'));try{await withServer({},async baseUrl=>{const result=await runBarrier(baseUrl,output);assert.equal(result.code,0,result.stderr);assert.match(result.stdout,/"status":"pass"/);for(const file of ['runtime-evidence.json','root-entry-runtime-evidence.json','studio-runtime-evidence.json','academy-runtime-evidence.json','readiness-runtime-evidence.json','cockpit-runtime-evidence.json','production-academy-status.json','production-readiness-v1.json','production-cockpit-v1.json','root-entry-v1.json'])await readFile(join(output,file),'utf8');});}finally{await rm(output,{recursive:true,force:true});}});
test('barrier fails closed when root entry remains stale',async()=>{const output=await mkdtemp(join(tmpdir(),'comic-public-barrier-stale-'));try{await withServer({'/proof/root-entry/root-entry-runtime-evidence.json':{...payloads['/proof/root-entry/root-entry-runtime-evidence.json'],commit:'stale-commit'}},async baseUrl=>{const result=await runBarrier(baseUrl,output);assert.notEqual(result.code,0);assert.match(result.stderr,/PUBLIC_BARRIER:TIMEOUT/);assert.match(result.stdout,/root-entry:CONTRACT_PENDING:stale-commit/);});}finally{await rm(output,{recursive:true,force:true});}});
