import { createHash } from 'node:crypto';
import { access, readFile, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const value=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const dir=resolve(value('--dir','/tmp/public-proof'));const expected=value('--expect-commit',process.env.GITHUB_SHA||'');
const fail=(code,detail='')=>{throw new Error(`[PUBLIC_ACADEMY:${code}]${detail?` ${detail}`:''}`);};const ok=(c,code,detail='')=>{if(!c)fail(code,detail);};async function req(p,min=1){const f=resolve(dir,p);try{await access(f);}catch{fail('MISSING',p);}const s=await stat(f);ok(s.size>=min,'EMPTY',p);return f;}async function json(p){return JSON.parse(await readFile(await req(p),'utf8'));}async function sha(p){return createHash('sha256').update(await readFile(await req(p))).digest('hex');}
ok(Boolean(expected),'EXPECTED_COMMIT');for(const f of ['production-academy.json','production-academy-status.json','academy-runtime-evidence.json','academy-desktop.png','academy-mobile.png','live-academy/academy-runtime-evidence.json','live-academy/academy-desktop.png','live-academy/academy-mobile.png'])await req(f,f.endsWith('.png')?10000:100);
const [contract,status,deployed,live]=await Promise.all([json('production-academy.json'),json('production-academy-status.json'),json('academy-runtime-evidence.json'),json('live-academy/academy-runtime-evidence.json')]);
ok(contract.schemaVersion===1,'CONTRACT_SCHEMA');ok(contract.trackingIssue===94,'CONTRACT_TRACKING');ok(contract.stages.length===12,'CONTRACT_STAGES');ok(contract.stages.slice(1).every(s=>s.automaticApprovalAllowed===false),'HUMAN_GATES');
ok(status.status==='proven_guided_training_ready_novice_acceptance_open','STATUS',status.status);ok(status.route==='/studio/#academy','ROUTE');ok(status.safety.humanGatesAutomaticallyApproved===false,'HUMAN_BOUNDARY');ok(status.safety.finalEpisodeAutomaticallyApproved===false,'EPISODE_BOUNDARY');ok(status.readiness.status==='NOT_PRODUCTION_READY','READINESS_STATUS');ok(status.readiness.productionReady===false,'PRODUCTION_READY');ok(status.readiness.beginnerReady===false,'BEGINNER_READY');ok(status.readiness.observedNoviceRunPassed===false,'NOVICE_RUN');ok(status.readiness.completeReviewedEpisodeExists===false,'EPISODE_EXISTS');ok(status.currentCreativeTruth.riccoCandidates===0,'RICCO');ok(status.currentCreativeTruth.imageGenerationAllowed===false,'GENERATION');
for(const [label,r] of [['deployed',deployed],['live',live]]){ok(r.status==='pass','RUNTIME',label);ok(r.commit===expected,'COMMIT',label);ok(r.stageCount===12,'STAGES',label);ok(r.trainingPathPassed&&r.productionHumanGatesPassed&&r.resumePassed,'FLOW',label);ok(r.creativeApprovalGranted===false,'CREATIVE',label);ok(r.finalEpisodeApprovalGranted===false,'EPISODE',label);ok(r.targets.length===2,'TARGETS',label);for(const t of r.targets){const n=`${label}:${t.target?.name||'unknown'}`;ok(t.initial.stageCount===12,'VISIBLE_STAGES',n);ok(t.initial.disabledCount===11,'VISIBLE_LOCKS',n);ok(t.initial.progressText.includes('0/12'),'VISIBLE_PROGRESS',n);ok(t.initial.forbiddenAutoApproval===false,'VISIBLE_APPROVAL',n);ok(t.initial.horizontalOverflowPixels<=2,'OVERFLOW',n);ok(t.training.firstStatus==='training_complete','TRAINING',n);ok(t.production.seriesBible==='review_required','REVIEW',n);ok(t.production.creativeApproved===false,'PRODUCTION_CREATIVE',n);ok(t.resumed===true,'RESUME',n);}}
const dd=await sha('academy-desktop.png'),dm=await sha('academy-mobile.png'),ld=await sha('live-academy/academy-desktop.png'),lm=await sha('live-academy/academy-mobile.png');ok(deployed.targets.find(t=>t.target?.name==='desktop')?.sha256===dd,'DEPLOYED_DESKTOP');ok(deployed.targets.find(t=>t.target?.name==='mobile')?.sha256===dm,'DEPLOYED_MOBILE');ok(live.targets.find(t=>t.target?.name==='desktop')?.sha256===ld,'LIVE_DESKTOP');ok(live.targets.find(t=>t.target?.name==='mobile')?.sha256===lm,'LIVE_MOBILE');
console.log(JSON.stringify({status:'pass',expectedCommit:expected,trackingIssue:94,stageCount:12,readiness:'NOT_PRODUCTION_READY',productionReady:false,beginnerReady:false,observedNoviceRunPassed:false,creativeApprovalGranted:false,finalEpisodeApprovalGranted:false,deployedDesktopHash:dd,deployedMobileHash:dm,liveDesktopHash:ld,liveMobileHash:lm},null,2));
