import { access, readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
const root = new URL('../', import.meta.url);
const readJson = async (path) => JSON.parse(await readFile(new URL(path, root), 'utf8'));
const required = [
  'README.md','index.html','app.js','lr1-ui.js','audit-ui.js','styles.css','m1.css','audit.css','package.json',
  'api/bot.mjs','api/health.mjs','lib/context.mjs','lib/browser-director.mjs',
  'project/project.json','project/truth-state.json','project/line-reset-closure.json','project/canon-candidates.json','project/pilot-decision-record.json','project/canon.json','project/evidence-closure.json',
  'project/studio-foundation-inventory.json','project/studio-foundation-status.json','project/studio-foundation-closure.json','project/lr3-production-loop-inventory.json','project/lr3-production-loop-closure.json','project/lr4-selected-pilot-source-inventory.json','project/lr4-selected-pilot-closure.json',
  'project/character-library.json','project/character-production-sheets.json','project/lora-training-sheets.json',
  'docs/TRUTH_AUDIT_2026-07-11.md','docs/LINE_RESET_CLOSURE_AUDIT_2026-07-11.md','docs/PILOT_DECISION_RECORD_2026-07-11.md','docs/STUDIO_FOUNDATION_RECOVERY_2026-07-11.md','docs/LR3_MINIMAL_PRODUCTION_LOOP.md','docs/LR4_SELECTED_PILOT_FIRE_TEST.md','docs/PRODUCTION_APP_RECOVERY_PLAN.md',
  'scripts/recover_assets.py','scripts/render_m1.py','.github/workflows/ci.yml','.github/workflows/pages.yml'
];
for (const file of required) await access(new URL(file, root));
const [project, truth, lr0Closure, decisionRecord, canon, evidenceClosure, foundationStatus, foundationClosure, loopClosure, pilotClosure, characters, sheets, loras] = await Promise.all([
  'project/project.json','project/truth-state.json','project/line-reset-closure.json','project/pilot-decision-record.json','project/canon.json','project/evidence-closure.json','project/studio-foundation-status.json','project/studio-foundation-closure.json','project/lr3-production-loop-closure.json','project/lr4-selected-pilot-closure.json','project/character-library.json','project/character-production-sheets.json','project/lora-training-sheets.json'
].map(readJson));
if (truth.repository !== 'Pagebabe/comic' || truth.status !== 'recovery_line_active' || truth.authority !== 'current_project_truth') throw new Error('Truth state is not authoritative.');
if (truth.trackingIssue !== 82 || truth.nextSequence?.find((item) => item.id === 'LR3')?.status !== 'done' || truth.nextSequence?.find((item) => item.id === 'LR4')?.status !== 'done' || truth.nextSequence?.find((item) => item.id === 'LR5')?.status !== 'active_recovery_gate') throw new Error('LR4 closure or LR5 activation drifted.');
if (truth.nextSequence?.find((item) => item.id === 'LR4')?.trackingIssue !== 76 || truth.nextSequence?.find((item) => item.id === 'LR5')?.trackingIssue !== 82) throw new Error('Recovery tracking issues drifted.');
if (truth.evidence.currentCoveragePercent !== null || truth.evidence.percentageClaimAllowed !== false) throw new Error('Current evidence must not expose a percentage.');
if (truth.canon.status !== 'pilot_selected_human_confirmed' || truth.canon.selectedPilot !== 'pilot-das-zimmer' || truth.canon.selectedTitle !== 'Das Zimmer') throw new Error('Human pilot selection is missing.');
if (truth.productArchitecture.currentMain.type !== 'audit_dashboard_with_verified_studio_neutral_loop_and_selected_pilot_transport') throw new Error('Current architecture does not disclose the verified selected-pilot path.');
if (truth.productArchitecture.productionFoundation.status !== 'neutral_foundation_loop_and_selected_pilot_transport_publicly_verified') throw new Error('Production Foundation boundary drifted.');
if (lr0Closure.status !== 'closed_verified' || lr0Closure.pullRequest !== 37 || lr0Closure.mergeCommit !== '47b513c31d5326efdf5bd8c81e835233f97b6b47') throw new Error('LR0 closure proof drifted.');
if (decisionRecord.status !== 'human_decision_recorded' || decisionRecord.selectedCandidateId !== 'pilot-das-zimmer' || decisionRecord.sourceRecord?.userConfirmation !== 'ok') throw new Error('Human pilot decision record is invalid.');
if (canon.authorityStatus !== 'pilot_selected_human_confirmed_detail_reviews_open' || canon.selectedPilot !== 'pilot-das-zimmer') throw new Error('Canon file does not preserve the narrow pilot selection.');
if (foundationStatus.status !== 'public_build_verified_closed' || foundationStatus.productionReady !== false || foundationStatus.productionLoopRestored !== false || foundationStatus.nextGate?.trackingIssue !== 60) throw new Error('Historical LR2 status boundary drifted.');
if (foundationClosure.status !== 'closed_verified' || foundationClosure.pullRequest?.number !== 59 || foundationClosure.pullRequest?.ciRun !== 29148650720 || foundationClosure.pullRequest?.mergeCommit !== '18d0c34b81db781305941c0e9f34c308ac5c8b76' || foundationClosure.deployment?.runId !== 29148728164 || foundationClosure.deployment?.publicVerificationPassed !== true) throw new Error('LR2 closure proof drifted.');
if (loopClosure.status !== 'closed_verified' || loopClosure.implementedBy?.pullRequest !== 74 || loopClosure.implementedBy?.ciRun !== 29150833651 || loopClosure.implementedBy?.mergeCommit !== '0226b80ae36457c95efb2e4dbbb0546623d274ae' || loopClosure.publicProof?.pagesRun !== 29150875221 || loopClosure.publicProof?.publicVerificationPassed !== true) throw new Error('LR3 closure proof drifted.');
if (loopClosure.proof?.stationsPassed !== 9 || !loopClosure.proof?.deleteCountercheckPassed || !loopClosure.proof?.deleteRestoreHashMatch || loopClosure.proof?.imageBytesUsed || loopClosure.proof?.externalExecutionUsed || loopClosure.proof?.creativeApprovalGranted || loopClosure.nextGate?.trackingIssue !== 76) throw new Error('LR3 technical proof or handoff drifted.');
if (pilotClosure.status !== 'closed_verified' || pilotClosure.implementedBy?.pullRequest !== 81 || pilotClosure.implementedBy?.verifiedHead !== 'a55a24e24bdae0bbf2b980f2842f57f0653092ca' || pilotClosure.implementedBy?.ciRun !== 29152706460 || pilotClosure.implementedBy?.mergeCommit !== '63021f49152dee7375578537be13dafd65685391' || pilotClosure.publicProof?.pagesRun !== 29152807415 || pilotClosure.publicProof?.publicVerificationPassed !== true) throw new Error('LR4 closure proof drifted.');
if (pilotClosure.proof?.stationsPassed !== 9 || pilotClosure.proof?.panelCount !== 8 || pilotClosure.proof?.dialogueCueCount !== 10 || pilotClosure.proof?.candidateDurationSeconds !== 45.5 || !pilotClosure.proof?.stateActuallyDeleted || !pilotClosure.proof?.packageRetainedDuringDeletion || !pilotClosure.proof?.deleteRestoreHashMatch || pilotClosure.proof?.stateHash !== '97b8216fbb11059a5f8fa0e3748ea8fa1e03706e15174c307ffe9ce84ca8c2cf' || pilotClosure.proof?.packageHash !== 'b6d2c8814dfc5cc558c5d7dd81113e71eafc51f531515fd7b4e9e8ec5a2ad196' || pilotClosure.proof?.imageBytesUsed || pilotClosure.proof?.externalExecutionUsed || pilotClosure.proof?.creativeApprovalGranted || pilotClosure.nextGate?.trackingIssue !== 82) throw new Error('LR4 technical proof or LR5 handoff drifted.');
if (evidenceClosure.status !== 'historical_bounded_snapshot' || evidenceClosure.currentCompletenessClaimAllowed !== false || evidenceClosure.snapshotThroughPullRequest !== 30) throw new Error('Historical closure is not bounded correctly.');
if (project.lineStatus !== 'recovery_line_active' || project.activeMilestone !== 'LR5' || project.activeTrackingIssue !== 82 || project.selectedPilot !== 'pilot-das-zimmer') throw new Error('Project state is not on LR5.');
if (project.inventory.visualCharacterMastersLocked !== 0 || project.inventory.approvedVoiceSamples !== 0 || project.inventory.approvedAnimaticPanelImages !== 0 || project.inventory.finishedEpisodes !== 0 || project.inventory.productionLoopRestored !== true || project.inventory.selectedPilotFireTestPassed !== true) throw new Error('Current production boundary was misreported.');
if (characters.length !== 13 || sheets.length !== 9 || loras.length !== 6) throw new Error('Preserved library counts drifted.');
for (const file of ['app.js','lr1-ui.js','audit-ui.js','api/bot.mjs','api/health.mjs','lib/context.mjs','lib/browser-director.mjs','scripts/check.mjs','scripts/check_evidence_chain.mjs','scripts/check_studio_foundation.mjs','scripts/check_production_loop.mjs','scripts/check_selected_pilot_loop.mjs','scripts/build_visual_proof.mjs']) {
  const result=spawnSync(process.execPath,['--check',new URL(file,root).pathname],{encoding:'utf8'}); if(result.status!==0) throw new Error(`Syntax check failed for ${file}: ${result.stderr}`);
}
for (const file of ['scripts/recover_assets.py','scripts/render_m1.py']) { const result=spawnSync('python3',['-m','py_compile',new URL(file,root).pathname],{encoding:'utf8'}); if(result.status!==0) throw new Error(`Python syntax failed for ${file}: ${result.stderr}`); }
const [readme,phaseUi,audit,context,recoveryPlan] = await Promise.all(['README.md','lr1-ui.js','audit-ui.js','lib/context.mjs','docs/PRODUCTION_APP_RECOVERY_PLAN.md'].map((path)=>readFile(new URL(path,root),'utf8')));
for (const marker of ['LR4 Das-Zimmer-Fire-Test:  geschlossen','aktives Gate:              LR5 VISUAL-, SET- UND VOICE-LOCKS','Issue #82','keine Prozentzahl']) if(!readme.includes(marker)) throw new Error(`README marker missing: ${marker}`);
for (const marker of ['LR4 PILOT FIRE TEST','LR5','Issue #82','lr4-selected-pilot-closure.json']) if(!phaseUi.includes(marker)) throw new Error(`Dashboard marker missing: ${marker}`);
for (const marker of ['AKTUELLE AUTORITÄT','HISTORISCHER SNAPSHOT']) if(!audit.includes(marker)) throw new Error(`Audit marker missing: ${marker}`);
for (const marker of ['aktives Gate: LR5 Visual-, Set- und Voice-Locks','Issue #82','Pages 29152807415']) if(!context.includes(marker)) throw new Error(`Director marker missing: ${marker}`);
for (const forbidden of ['BEWEISKETTE 100% GESCHLOSSEN','kein Kandidat ist ausgewählt','aktives Gate: LR2 Studio Foundation retten','aktives Gate: LR3 minimalen Produktionsloop retten','aktives Gate: LR4 Selected-Pilot-Fire-Test']) if(phaseUi.includes(forbidden)||context.includes(forbidden)||readme.includes(forbidden)) throw new Error(`Current truth still contains forbidden claim: ${forbidden}`);
if (!/Control[\s\S]*Studio[\s\S]*Prompt Queue[\s\S]*Restore/.test(recoveryPlan)) throw new Error('Recovery plan lacks the production loop sequence.');
console.log(JSON.stringify({status:'pass',repository:truth.repository,lineStatus:truth.status,closedGate:'LR4',activeGate:'LR5',trackingIssue:82,selectedPilot:'pilot-das-zimmer',currentEvidenceCoveragePercent:null,productionLoopRestored:true,selectedPilotFireTestPassed:true,characterMastersApproved:0,locationMastersApproved:0,voiceMastersApproved:0}));
