import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const value=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const site=resolve(value('--site','_site'));const expected=value('--expect-commit',process.env.GITHUB_SHA||'');
const fail=(code,detail='')=>{throw new Error(`[READINESS_ARTIFACT:${code}]${detail?` ${detail}`:''}`);};const ok=(c,code,detail='')=>{if(!c)fail(code,detail);};
async function req(p){const f=resolve(site,p);try{await access(f);}catch{fail('MISSING',p);}return f;}async function json(p){return JSON.parse(await readFile(await req(p),'utf8'));}
for(const file of ['project/production-readiness-v1.json','project/novice-acceptance-template.json','docs/NOVICE_ACCEPTANCE_PROTOCOL.md','proof/readiness/academy-readiness-runtime-evidence.json','proof/readiness/academy-readiness-desktop.png','proof/readiness/academy-readiness-mobile.png'])await req(file);
const [r,a,p]=await Promise.all([json('project/production-readiness-v1.json'),json('project/novice-acceptance-template.json'),json('proof/readiness/academy-readiness-runtime-evidence.json')]);
ok(Boolean(expected),'EXPECTED_COMMIT');ok(r.status==='NOT_PRODUCTION_READY','STATUS');ok(r.currentScore.display==='2/10 CLOSED_VERIFIED · 7 PARTIAL · 1 OPEN','SCORE');ok(r.gates.length===10,'GATES');ok(r.academyBoundary.productionReady===false,'PRODUCTION');ok(r.academyBoundary.beginnerReady===false,'BEGINNER');ok(r.academyBoundary.imageGenerationAllowed===false,'IMAGE');ok(r.academyBoundary.creativeApprovalGranted===false,'CREATIVE');ok(r.academyBoundary.growthOsIntegrated===false,'GROWTH');ok(r.parallelLineBoundary.sharedIntegrationSmokePassed===false,'GROWTH_SMOKE');
ok(a.status==='TEMPLATE_NOT_EXECUTED','ACCEPTANCE_STATUS');ok(a.tasks.length===12,'TASKS');ok(a.result.decision==='NOT_EXECUTED','ACCEPTANCE_DECISION');
ok(p.status==='pass','PROOF_STATUS');ok(p.commit===expected,'PROOF_COMMIT',`${p.commit} != ${expected}`);ok(p.readinessScore===r.currentScore.display,'PROOF_SCORE');ok(p.stages===12,'STAGES');ok(p.readinessGates===10,'PROOF_GATES');ok(p.noviceTasks===12,'PROOF_TASKS');ok(p.trainingBoundaryPassed&&p.resetPassed,'PROOF_FLOW');for(const key of ['productionReady','beginnerReady','observedNoviceRunPassed','completeReviewedEpisodeExists','imageGenerationAllowed','creativeApprovalGranted','growthOsIntegrated','sharedGrowthIntegrationSmokePassed'])ok(p[key]===false,`PROOF_${key}`);ok(p.externalRequests===0,'EXTERNAL');ok(p.targets.length===2,'TARGETS');for(const t of p.targets){ok(t.checks.gateCount===10,'VISIBLE_GATES',t.name);ok(t.checks.tasks===12,'VISIBLE_TASKS',t.name);ok(t.checks.productionFalse&&t.checks.beginnerFalse&&t.checks.imageBlocked&&t.checks.growthSeparated,'VISIBLE_BOUNDARY',t.name);ok(t.checks.overflow<=2,'OVERFLOW',t.name);ok(Boolean(t.sha256),'HASH',t.name);}
console.log(JSON.stringify({status:'pass',expectedCommit,readiness:r.currentScore.display,stages:12,gates:10,tasks:12,productionReady:false,beginnerReady:false,creativeApprovalGranted:false,targets:2},null,2));
