import { createHash } from 'node:crypto';
import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const value=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const dir=resolve(value('--dir','/tmp/public-proof'));const expected=value('--expect-commit',process.env.GITHUB_SHA||'');
const fail=(code,detail='')=>{throw new Error(`[ROOT_ENTRY_PUBLIC:${code}]${detail?` ${detail}`:''}`);};const ok=(c,code,detail='')=>{if(!c)fail(code,detail);};async function req(p){const f=resolve(dir,p);try{await access(f);}catch{fail('MISSING',p);}return f;}async function json(p){return JSON.parse(await readFile(await req(p),'utf8'));}async function sha(p){return createHash('sha256').update(await readFile(await req(p))).digest('hex');}
for(const f of ['root-entry-v1.json','root-entry-runtime-evidence.json','root-entry-desktop.png','root-entry-mobile.png','live-root/root-entry-runtime-evidence.json','live-root/root-entry-desktop.png','live-root/root-entry-mobile.png'])await req(f);
const [contract,deployed,live]=await Promise.all([json('root-entry-v1.json'),json('root-entry-runtime-evidence.json'),json('live-root/root-entry-runtime-evidence.json')]);
ok(Boolean(expected),'EXPECTED_COMMIT');ok(contract.status==='ROOT_ENTRY_READY_FOR_PROOF','STATUS');ok(contract.primaryAction.href==='./studio/#cockpit','PRIMARY');ok(contract.legacyAudit.route==='/audit.html','AUDIT');ok(Object.values(contract.boundaries).every(v=>v===false),'BOUNDARIES');
for(const [label,p] of [['deployed',deployed],['live',live]]){ok(p.status==='pass','PROOF_STATUS',label);ok(p.commit===expected,'PROOF_COMMIT',label);ok(p.primaryAction==='./studio/#cockpit','PROOF_PRIMARY',label);ok(p.auditRoute==='./audit.html','PROOF_AUDIT',label);ok(p.entryCards===4&&p.stateCards===5&&p.boundaries===4,'COUNTS',label);ok(p.externalRequests===0&&p.scriptCount===0&&p.buttonCount===0&&p.imageCount===0&&p.canvasCount===0&&p.iframeCount===0,'SURFACE',label);ok(p.riccoCandidates===0&&!p.productionReady&&!p.beginnerReady&&!p.imageGenerationAllowed&&!p.growthOsIntegrated,'STATE',label);ok(p.targets.length===2,'TARGETS',label);for(const t of p.targets){ok(t.checks.primaryHref==='./studio/#cockpit','VISIBLE_PRIMARY',`${label}:${t.name}`);ok(!t.checks.staleLr1Copy,'STALE',`${label}:${t.name}`);ok(t.checks.overflow<=2,'OVERFLOW',`${label}:${t.name}`);}}
for(const t of deployed.targets)ok(await sha(`root-entry-${t.name}.png`)===t.sha256,'DEPLOYED_HASH',t.name);for(const t of live.targets)ok(await sha(`live-root/root-entry-${t.name}.png`)===t.sha256,'LIVE_HASH',t.name);
ok(deployed.primaryAction===live.primaryAction&&deployed.auditRoute===live.auditRoute&&deployed.riccoCandidates===live.riccoCandidates,'SEMANTIC_DRIFT');
console.log(JSON.stringify({status:'pass',expectedCommit:expected,route:'/',primaryAction:'./studio/#cockpit',auditRoute:'./audit.html',semanticStateMatched:true,productionReady:false,beginnerReady:false},null,2));
