import { createHash } from 'node:crypto';
import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const value=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const dir=resolve(value('--dir','/tmp/public-proof'));const expected=value('--expect-commit',process.env.GITHUB_SHA||'');
const fail=(code,detail='')=>{throw new Error(`[READINESS_PUBLIC:${code}]${detail?` ${detail}`:''}`);};const ok=(c,code,detail='')=>{if(!c)fail(code,detail);};async function req(p){const f=resolve(dir,p);try{await access(f);}catch{fail('MISSING',p);}return f;}async function json(p){return JSON.parse(await readFile(await req(p),'utf8'));}async function sha(p){return createHash('sha256').update(await readFile(await req(p))).digest('hex');}
for(const file of ['production-readiness-v1.json','novice-acceptance-template.json','readiness-runtime-evidence.json','readiness-desktop.png','readiness-mobile.png','live-readiness/academy-readiness-runtime-evidence.json','live-readiness/academy-readiness-desktop.png','live-readiness/academy-readiness-mobile.png'])await req(file);
const [r,a,deployed,live]=await Promise.all([json('production-readiness-v1.json'),json('novice-acceptance-template.json'),json('readiness-runtime-evidence.json'),json('live-readiness/academy-readiness-runtime-evidence.json')]);
ok(Boolean(expected),'EXPECTED_COMMIT');ok(r.status==='NOT_PRODUCTION_READY','STATUS');ok(r.currentScore.display==='2/10 CLOSED_VERIFIED · 7 PARTIAL · 1 OPEN','SCORE');ok(r.gates.length===10,'GATES');ok(a.status==='TEMPLATE_NOT_EXECUTED','ACCEPTANCE');ok(a.tasks.length===12,'TASKS');
for(const [label,p] of [['deployed',deployed],['live',live]]){ok(p.status==='pass','PROOF_STATUS',label);ok(p.commit===expected,'PROOF_COMMIT',label);ok(p.readinessScore===r.currentScore.display,'PROOF_SCORE',label);ok(p.stages===12&&p.readinessGates===10&&p.noviceTasks===12,'COUNTS',label);ok(p.trainingBoundaryPassed&&p.resetPassed,'FLOW',label);for(const key of ['productionReady','beginnerReady','observedNoviceRunPassed','completeReviewedEpisodeExists','imageGenerationAllowed','creativeApprovalGranted','growthOsIntegrated','sharedGrowthIntegrationSmokePassed'])ok(p[key]===false,`${label}_${key}`);ok(p.externalRequests===0,'EXTERNAL',label);ok(p.targets.length===2,'TARGETS',label);for(const t of p.targets){ok(t.checks.gateCount===10,'VISIBLE_GATES',`${label}:${t.name}`);ok(t.checks.tasks===12,'VISIBLE_TASKS',`${label}:${t.name}`);ok(t.checks.productionFalse&&t.checks.beginnerFalse&&t.checks.imageBlocked&&t.checks.growthSeparated,'VISIBLE_BOUNDARY',`${label}:${t.name}`);ok(t.checks.overflow<=2,'OVERFLOW',`${label}:${t.name}`);}}
for(const t of deployed.targets){const actual=await sha(`readiness-${t.name}.png`);ok(actual===t.sha256,'DEPLOYED_HASH',t.name);const lt=live.targets.find(x=>x.name===t.name);ok(Boolean(lt)&&lt.sha256===t.sha256,'LIVE_MATCH',t.name);const liveActual=await sha(`live-readiness/academy-readiness-${t.name}.png`);ok(liveActual===lt.sha256,'LIVE_HASH',t.name);}
console.log(JSON.stringify({status:'pass',expectedCommit:expected,readiness:r.currentScore.display,productionReady:false,beginnerReady:false,observedNoviceRunPassed:false,completeReviewedEpisodeExists:false,creativeApprovalGranted:false,screenshotHashesMatched:true},null,2));
