import { readFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);const j=async p=>JSON.parse(await readFile(new URL(p,root),'utf8'));
const [truth,closure,history,policy,candidates,decision,project]=await Promise.all(['project/truth-state.json','project/evidence-closure.json','project/historical-pr-evidence.json','project/evidence-policy-rules.json','project/canon-candidates.json','project/pilot-decision-record.json','project/project.json'].map(j));
if(truth.repository!=='Pagebabe/comic'||truth.authority!=='current_project_truth')throw new Error('Truth state is not current authority.');
if(truth.evidence.percentageClaimAllowed!==false||truth.evidence.currentCoveragePercent!==null)throw new Error('Current percentage claim is not disabled.');
if(closure.status!=='historical_bounded_snapshot'||closure.authorityStatus!=='superseded_as_current_truth')throw new Error('Old closure is not bounded.');
if(closure.snapshotThroughPullRequest!==30||closure.currentCompletenessClaimAllowed!==false)throw new Error('Old snapshot boundary is invalid.');
if(history.scope?.coveredPullRequestNumbers?.at(-1)!==30)throw new Error('Historical ledger boundary must remain explicit at PR #30.');
if(policy.priority!==0||policy.status!=='active')throw new Error('Evidence-first process rule must remain active.');
if(decision.status!=='human_decision_recorded'||decision.selectedCandidateId!=='pilot-das-zimmer'||decision.decidedBy!=='project_owner_user'||decision.sourceRecord?.userConfirmation!=='ok')throw new Error('Selected pilot lacks the explicit human decision record.');
if(candidates.selectedCandidateId!==decision.selectedCandidateId||truth.canon.selectedPilot!==decision.selectedCandidateId||project.selectedPilot!==decision.selectedCandidateId)throw new Error('Pilot selection sources disagree.');
if(candidates.candidates.find(x=>x.id==='pilot-der-solidarpreis')?.status!=='archived_not_selected')throw new Error('Unselected candidate is not traceably archived.');
if(truth.canon.status!=='pilot_selected_human_confirmed'||project.canonAuthority!=='pilot_selected_human_confirmed'||truth.nextSequence?.find(x=>x.id==='LR2')?.status!=='active_recovery_gate')throw new Error('Human selection did not hand off cleanly to LR2.');
if(!decision.selectionScope?.notAutomaticallyApproved?.includes('every existing dialogue line'))throw new Error('Pilot selection boundary does not preserve detail review gates.');
if(project.inventory.visualCharacterMastersLocked!==0||project.inventory.approvedVoiceSamples!==0||project.inventory.finishedEpisodes!==0)throw new Error('Unbuilt product work was claimed.');
console.log(JSON.stringify({status:'pass',repository:truth.repository,currentAuthority:'project/truth-state.json',currentEvidenceCoveragePercent:null,historicalSnapshot:{throughPullRequest:closure.snapshotThroughPullRequest,selectedEntries:closure.coverage.trackedEntries},canonStatus:truth.canon.status,selectedPilot:decision.selectedCandidateId,decisionStatus:decision.status,activeGate:'LR2'}));
