import { createHash } from 'node:crypto';
import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const value=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const site=resolve(value('--site','_site'));const expected=value('--expect-commit',process.env.GITHUB_SHA||'');
const fail=(code,detail='')=>{throw new Error(`[ROOT_ENTRY_ARTIFACT:${code}]${detail?` ${detail}`:''}`);};const ok=(c,code,detail='')=>{if(!c)fail(code,detail);};
async function req(p){const f=resolve(site,p);try{await access(f);}catch{fail('MISSING',p);}return f;}async function json(p){return JSON.parse(await readFile(await req(p),'utf8'));}async function sha(p){return createHash('sha256').update(await readFile(await req(p))).digest('hex');}
for(const f of ['index.html','audit.html','gateway.css','project/root-entry-v1.json','proof/root-entry/root-entry-runtime-evidence.json','proof/root-entry/root-entry-desktop.png','proof/root-entry/root-entry-mobile.png'])await req(f);
const [contract,proof]=await Promise.all([json('project/root-entry-v1.json'),json('proof/root-entry/root-entry-runtime-evidence.json')]);
ok(Boolean(expected),'EXPECTED_COMMIT');ok(contract.status==='ROOT_ENTRY_READY_FOR_PROOF','STATUS');ok(contract.primaryAction.href==='./studio/#cockpit','PRIMARY');ok(contract.legacyAudit.preserved&&contract.legacyAudit.route==='/audit.html','AUDIT');ok(contract.currentState.riccoCandidates===0,'CANDIDATE');ok(!contract.currentState.productionReady&&!contract.currentState.beginnerReady,'READINESS');ok(Object.values(contract.boundaries).every(v=>v===false),'BOUNDARIES');
ok(proof.status==='pass','PROOF_STATUS');ok(proof.commit===expected,'PROOF_COMMIT');ok(proof.primaryAction==='./studio/#cockpit','PROOF_PRIMARY');ok(proof.auditRoute==='./audit.html','PROOF_AUDIT');ok(proof.targets.length===2,'TARGETS');for(const t of proof.targets){ok(t.checks.entryCards===4,'CARDS',t.name);ok(t.checks.stateCards===5,'STATE',t.name);ok(t.checks.boundaries===4,'BOUNDARIES_VISIBLE',t.name);ok(!t.checks.staleLr1Copy,'STALE',t.name);ok(t.checks.overflow<=2,'OVERFLOW',t.name);ok(Boolean(t.sha256),'HASH',t.name);ok(await sha(`proof/root-entry/root-entry-${t.name}.png`)===t.sha256,'HASH_MATCH',t.name);}
console.log(JSON.stringify({status:'pass',expectedCommit:expected,route:'/',primaryAction:'./studio/#cockpit',auditRoute:'./audit.html',targets:2,productionReady:false,beginnerReady:false},null,2));
