import { createHash } from 'node:crypto';
import { access, readFile, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const value=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const site=resolve(value('--site','_site'));const expected=value('--expect-commit',process.env.GITHUB_SHA||'');
const fail=(code,detail='')=>{throw new Error(`[ACADEMY_PAGES_ARTIFACT:${code}]${detail?` ${detail}`:''}`);};const ok=(c,code,detail='')=>{if(!c)fail(code,detail);};async function req(p,min=1){const f=resolve(site,p);try{await access(f);}catch{fail('MISSING',p);}const s=await stat(f);ok(s.size>=min,'EMPTY',p);return f;}async function json(p){return JSON.parse(await readFile(await req(p),'utf8'));}async function sha(p){return createHash('sha256').update(await readFile(await req(p))).digest('hex');}
ok(Boolean(expected),'EXPECTED_COMMIT');for(const f of ['project/production-academy.json','project/production-academy-status.json','docs/PRODUCTION_HANDBOOK_DE.md','docs/QUICKSTART_DAY_ONE.md','docs/VIDEO_TUTORIAL_SCRIPT_DE.md','docs/AUTOMATION_80_PERCENT_MODEL.md','docs/PRODUCTION_ACADEMY_EVIDENCE.md','proof/studio/academy-runtime-evidence.json','proof/studio/academy-desktop.png','proof/studio/academy-mobile.png'])await req(f,f.endsWith('.png')?10000:100);
const [contract,status,runtime]=await Promise.all([json('project/production-academy.json'),json('project/production-academy-status.json'),json('proof/studio/academy-runtime-evidence.json')]);
ok(contract.schemaVersion===1,'CONTRACT_SCHEMA');ok(contract.trackingIssue===94,'CONTRACT_TRACKING');ok(contract.stages.length===12,'CONTRACT_STAGES');ok(contract.stages[0].automaticApprovalAllowed===true,'FIRST_STAGE');ok(contract.stages.slice(1).every(s=>s.automaticApprovalAllowed===false),'HUMAN_GATES');
ok(status.status==='proven_guided_training_ready_novice_acceptance_open','STATUS',status.status);ok(status.route==='/studio/#academy','ROUTE');ok(status.implemented.guidedStages===12,'STATUS_STAGES');ok(status.safety.trainingGrantsProductionApproval===false,'TRAINING_BOUNDARY');ok(status.safety.humanGatesAutomaticallyApproved===false,'HUMAN_BOUNDARY');ok(status.safety.finalEpisodeAutomaticallyApproved===false,'EPISODE_BOUNDARY');ok(status.readiness.status==='NOT_PRODUCTION_READY','READINESS_STATUS');ok(status.readiness.productionReady===false,'PRODUCTION_READY');ok(status.readiness.beginnerReady===false,'BEGINNER_READY');ok(status.readiness.observedNoviceRunPassed===false,'NOVICE_RUN');ok(status.readiness.completeReviewedEpisodeExists===false,'EPISODE_EXISTS');ok(status.currentCreativeTruth.riccoCandidates===0,'RICCO');ok(status.currentCreativeTruth.imageGenerationAllowed===false,'GENERATION');
ok(runtime.status==='pass','RUNTIME');ok(runtime.commit===expected,'COMMIT');ok(runtime.stageCount===12,'RUNTIME_STAGES');ok(runtime.trainingPathPassed&&runtime.productionHumanGatesPassed&&runtime.resumePassed,'RUNTIME_FLOW');ok(runtime.creativeApprovalGranted===false,'RUNTIME_CREATIVE');ok(runtime.finalEpisodeApprovalGranted===false,'RUNTIME_EPISODE');ok(runtime.targets.length===2,'TARGETS');for(const t of runtime.targets){const n=t.target?.name||'unknown';ok(t.initial.stageCount===12,'VISIBLE_STAGES',n);ok(t.initial.disabledCount===11,'VISIBLE_LOCKS',n);ok(t.initial.progressText.includes('0/12'),'VISIBLE_PROGRESS',n);ok(t.initial.forbiddenAutoApproval===false,'VISIBLE_APPROVAL',n);ok(t.initial.horizontalOverflowPixels<=2,'OVERFLOW',n);ok(t.training.firstStatus==='training_complete','TRAINING',n);ok(t.production.seriesBible==='review_required','PRODUCTION_REVIEW',n);ok(t.production.creativeApproved===false,'PRODUCTION_CREATIVE',n);ok(t.resumed===true,'RESUME',n);}
const dh=await sha('proof/studio/academy-desktop.png'),mh=await sha('proof/studio/academy-mobile.png');ok(runtime.targets.find(t=>t.target?.name==='desktop')?.sha256===dh,'DESKTOP_HASH');ok(runtime.targets.find(t=>t.target?.name==='mobile')?.sha256===mh,'MOBILE_HASH');console.log(JSON.stringify({status:'pass',expectedCommit:expected,trackingIssue:94,stageCount:12,readiness:'NOT_PRODUCTION_READY',productionReady:false,beginnerReady:false,creativeApprovalGranted:false,desktopHash:dh,mobileHash:mh},null,2));
