import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const args=process.argv.slice(2);const valueAfter=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0?args[i+1]:fallback;};const baseUrl=new URL(valueAfter('--base-url','https://pagebabe.github.io/comic/'));const expectedCommit=valueAfter('--expect-commit',process.env.GITHUB_SHA||'');const outputDir=resolve(valueAfter('--output','/tmp/public-proof'));const attempts=Number(valueAfter('--attempts','30'));const delayMs=Number(valueAfter('--delay-ms','5000'));if(!expectedCommit)throw new Error('[PUBLIC_BARRIER:EXPECTED_COMMIT_MISSING]');if(!Number.isInteger(attempts)||attempts<1)throw new Error('[PUBLIC_BARRIER:INVALID_ATTEMPTS]');if(!Number.isInteger(delayMs)||delayMs<0)throw new Error('[PUBLIC_BARRIER:INVALID_DELAY]');
const targets=[
{id:'dashboard',path:'proof/runtime-evidence.json',output:'runtime-evidence.json',validate:(d)=>d.status==='pass'&&d.commit===expectedCommit&&d.activeGate==='LR5'&&d.activeWorkPackage==='LR5.1'&&d.route?.endsWith('/audit.html')},
{id:'root-entry',path:'proof/root-entry/root-entry-runtime-evidence.json',output:'root-entry-runtime-evidence.json',validate:(d)=>d.status==='pass'&&d.commit===expectedCommit&&d.trackingIssue===121&&d.parentIssue===117&&d.primaryAction==='./studio/#cockpit'&&d.auditRoute==='./audit.html'&&d.riccoCandidates===0&&d.productionReady===false&&d.beginnerReady===false&&d.imageGenerationAllowed===false&&d.growthOsIntegrated===false},
{id:'studio',path:'proof/studio/studio-runtime-evidence.json',output:'studio-runtime-evidence.json',validate:(d)=>d.status==='pass'&&d.commit===expectedCommit&&d.activeGate==='LR5'&&d.activeWorkPackage==='LR5.1'},
{id:'academy',path:'proof/studio/academy-runtime-evidence.json',output:'academy-runtime-evidence.json',validate:(d)=>d.status==='pass'&&d.commit===expectedCommit&&d.stageCount===12&&d.creativeApprovalGranted===false&&d.finalEpisodeApprovalGranted===false},
{id:'readiness',path:'proof/readiness/academy-readiness-runtime-evidence.json',output:'readiness-runtime-evidence.json',validate:(d)=>d.status==='pass'&&d.commit===expectedCommit&&d.readinessScore==='2/10 CLOSED_VERIFIED · 7 PARTIAL · 1 OPEN'&&d.productionReady===false&&d.beginnerReady===false&&d.creativeApprovalGranted===false},
{id:'cockpit',path:'proof/cockpit/production-cockpit-runtime-evidence.json',output:'cockpit-runtime-evidence.json',validate:(d)=>d.status==='pass'&&d.commit===expectedCommit&&d.trackingIssue===117&&d.activeGate==='LR5.1'&&d.activeWorkPackage===88&&d.workspaceCount===6&&d.riccoCandidates===0&&d.imageGenerationAllowed===false&&d.creativeApprovalGranted===false&&d.productionReady===false&&d.beginnerReady===false&&d.growthOsIntegrated===false},
{id:'academy-status',path:'project/production-academy-status.json',output:'production-academy-status.json',validate:(d)=>d.status==='proven_guided_training_ready_novice_acceptance_open'&&d.readiness?.productionReady===false&&d.readiness?.beginnerReady===false&&d.readiness?.observedNoviceRunPassed===false},
{id:'readiness-contract',path:'project/production-readiness-v1.json',output:'production-readiness-v1.json',validate:(d)=>d.status==='NOT_PRODUCTION_READY'&&d.currentScore?.display==='2/10 CLOSED_VERIFIED · 7 PARTIAL · 1 OPEN'&&d.academyBoundary?.productionReady===false&&d.academyBoundary?.beginnerReady===false},
{id:'cockpit-contract',path:'project/production-cockpit-v1.json',output:'production-cockpit-v1.json',validate:(d)=>d.status==='WORKING_COCKPIT_V1'&&d.route==='/studio/#cockpit'&&d.trackingIssue===117&&d.activeGate?.id==='LR5.1'&&d.activeGate?.trackingIssue===88&&d.nextAllowedStep?.decision==='CONTRACT_APPROVED_FOR_ONE_CANDIDATE'&&d.counts?.riccoCandidates===0&&d.sections?.length===6&&Object.values(d.boundaries||{}).every((entry)=>entry===false)},
{id:'root-entry-contract',path:'project/root-entry-v1.json',output:'root-entry-v1.json',validate:(d)=>d.status==='ROOT_ENTRY_READY_FOR_PROOF'&&d.route==='/'&&d.trackingIssue===121&&d.parentIssue===117&&d.primaryAction?.href==='./studio/#cockpit'&&d.legacyAudit?.preserved===true&&d.legacyAudit?.route==='/audit.html'&&d.currentState?.riccoCandidates===0&&d.currentState?.productionReady===false&&d.currentState?.beginnerReady===false&&Object.values(d.boundaries||{}).every((entry)=>entry===false)}];
await mkdir(outputDir,{recursive:true});const sleep=(ms)=>new Promise((r)=>setTimeout(r,ms));let lastPending=[];for(let attempt=1;attempt<=attempts;attempt+=1){const pending=[];const fetched=new Map();await Promise.all(targets.map(async(target)=>{const url=new URL(target.path,baseUrl);url.searchParams.set('sha',expectedCommit);url.searchParams.set('attempt',String(attempt));try{const response=await fetch(url,{headers:{'cache-control':'no-cache',pragma:'no-cache'}});if(!response.ok){pending.push(`${target.id}:HTTP_${response.status}`);return;}const data=await response.json();if(!target.validate(data)){const observed=data?.commit?`:${data.commit}`:'';pending.push(`${target.id}:CONTRACT_PENDING${observed}`);return;}fetched.set(target.id,{target,data});}catch(error){pending.push(`${target.id}:${error instanceof Error?error.message:String(error)}`);}}));if(pending.length===0&&fetched.size===targets.length){for(const{target,data}of fetched.values())await writeFile(resolve(outputDir,target.output),`${JSON.stringify(data,null,2)}\n`);console.log(JSON.stringify({status:'pass',expectedCommit,attempt,manifests:targets.map((target)=>target.id)}));process.exit(0);}lastPending=pending.sort();console.log(JSON.stringify({status:'pending',expectedCommit,attempt,pending:lastPending}));if(attempt<attempts)await sleep(delayMs);}throw new Error(`[PUBLIC_BARRIER:TIMEOUT] ${lastPending.join(', ')}`);
