import { timingSafeEqual } from 'node:crypto';
import { PROJECT_CONTEXT, COMMAND_HELP } from '../lib/context.mjs';

const DEFAULT_ALLOWED_HOSTS = new Set(['api.openai.com','openrouter.ai','api.deepseek.com','integrate.api.nvidia.com','api.groq.com','api.together.xyz','api.fireworks.ai']);
const sendJson = (response, status, payload) => { response.setHeader('Cache-Control','no-store'); response.setHeader('X-Content-Type-Options','nosniff'); return response.status(status).json(payload); };
const getHeader = (request, name) => { const value = request.headers?.get?.(name.toLowerCase()) ?? request.headers?.[name.toLowerCase()]; return Array.isArray(value) ? value[0] : value; };
const safeEqual = (left, right) => { if (typeof left !== 'string' || typeof right !== 'string') return false; const a=Buffer.from(left), b=Buffer.from(right); return a.length===b.length && timingSafeEqual(a,b); };
const parseBody = (body) => { if (body == null) return {}; if (typeof body === 'string') return JSON.parse(body); if (Buffer.isBuffer(body)) return JSON.parse(body.toString('utf8')); if (typeof body === 'object') return body; throw new Error('Unsupported body type'); };
const firstLine = (value) => String(value).split(/\r?\n/,1)[0].replace(/\s+/g,' ').trim().slice(0,100);

export function commandReply(message) {
  const match=String(message).trim().match(/^(\/[a-z-]+)(?:\s+([\s\S]*))?$/i); if(!match) return null;
  const command=match[1].toLowerCase(), argument=(match[2]||'').trim();
  switch(command){
    case '/status': return {reply:'Aktive Linie: LR5 Visual-, Set- und Voice-Locks · Issue #82. Einziges aktives Arbeitspaket: LR5.1 Ricco Visual-Master-Vertrag · Issue #88. Status CONTRACT_READY_REVIEW_REQUIRED. Quellen 7, Konflikte 5, Reviewtests 10, Kandidaten 0/1. Bildgenerierung, Batch, LoRA und automatische Masterfreigabe sind gesperrt. LR0 bis LR4 sind öffentlich geschlossen. Character-Master 0/4, Sets 0/4, Stimmen 0/3, fertige Episode nein.'};
    case '/next': return {reply:'Nächster Schritt: LR5.1-Vertrag, Quellenhierarchie, Nullzustand und sichtbare Desktop-/Mobil-Reviewroute durch CI und Pages beweisen. Danach ist eine ausdrückliche menschliche Entscheidung CONTRACT_APPROVED_FOR_ONE_CANDIDATE nötig. Erst dann darf genau ein Ricco-Review-Sheet erzeugt werden. Aktuell keine Bild-, GPU-, Provider- oder LoRA-Ausführung.'};
    case '/characters': return {reply:'Ricco, Basti Prenzl, Jule und Don Miau gehören zur ausgewählten Pilotlinie Das Zimmer. Ricco steht in LR5.1 bei 0/1 Kandidat und REVIEW_REQUIRED; sein Dashboard-SVG ist kein Master. Basti, Jule, Don Miau, alle Sets und Stimmen bleiben blockiert, bis der erste Ricco-Gate menschlich entschieden ist.'};
    case '/plan': return {reply:'LR0 Truth Reset ✓ → LR1 Das Zimmer ausgewählt ✓ → LR2 Studio Foundation ✓ → LR3 neutraler Delete-and-Restore-Loop ✓ → LR4 Das-Zimmer-Fire-Test ✓ → LR5 aktiv → LR5.1 Ricco-Vertrag REVIEW_REQUIRED, 0/1, Ausführung gesperrt → danach übrige Character-, Set- und Voice-Locks → LR6 erster echter Pilot.'};
    case '/task': { if(!argument) return {reply:'Format: /task <klarer Titel>'}; const title=firstLine(argument); const details=argument.includes('\n')?argument.slice(argument.indexOf('\n')+1).trim():''; return {reply:`LR5.1-Arbeitspaket vorbereitet: ${title}`, mutation:{title:`[LR5.1 WORK PACKET] ${title}`, body:`## Ziel\n${title}\n\n## Director-Entwurf\n${details||'Noch kein Detailentwurf hinterlegt.'}\n\n## Aktive Linie\nLR5 Parent-Gate · Issue #82\nLR5.1 Ricco Visual-Master-Vertrag · Issue #88\n\n## Wahrheitsstatus\n- LR0 bis LR4: öffentlich geschlossen\n- ausgewählter Pilot: Das Zimmer\n- Ricco-Vertrag: CONTRACT_READY_REVIEW_REQUIRED\n- Quellen: 7\n- Konflikte: 5\n- Kandidaten: 0/1\n- Bildgenerierung jetzt erlaubt: nein\n- Character-Master: 0/4\n- Location-Master: 0/4\n- Stimmen: 0/3\n- fertige Episode: nein\n\n## Stop-Regeln\n- keine Bildgenerierung vor CONTRACT_APPROVED_FOR_ONE_CANDIDATE\n- danach genau ein Ricco-Review-Sheet, kein Batch\n- kein LoRA-Training vor menschlich freigegebenem Ricco-Master\n- keine parallele Set-, Voice- oder weitere Character-Arbeit\n- keine automatische Masterfreigabe\n- kein Growth OS\n- ausschließlich Pagebabe/comic\n\n_Erstellt durch Comic Director._`}}; }
    case '/render': return {reply:`RENDER BLOCKED · ${argument ? firstLine(argument) : 'kein Shot angegeben'}. LR5.1 steht auf CONTRACT_READY_REVIEW_REQUIRED und 0/1 Kandidat. Vor CONTRACT_APPROVED_FOR_ONE_CANDIDATE wird weder ein Render-Issue noch eine Bild-, GPU-, Provider- oder LoRA-Ausführung vorbereitet.`};
    case '/help': return {reply:COMMAND_HELP}; default:return null;
  }
}

function allowedHosts(){ const hosts=new Set(DEFAULT_ALLOWED_HOSTS); for(const host of String(process.env.LLM_ALLOWED_HOSTS||'').split(',')) if(host.trim()) hosts.add(host.trim().toLowerCase()); try{if(process.env.LLM_BASE_URL) hosts.add(new URL(process.env.LLM_BASE_URL).hostname.toLowerCase());}catch{} return hosts; }
export function validateProviderUrl(value){ try{const url=new URL(String(value)),host=url.hostname.toLowerCase(),local=['localhost','127.0.0.1','::1'].includes(host); if(local&&process.env.NODE_ENV==='production') return null; if(local) return ['http:','https:'].includes(url.protocol)?url.toString().replace(/\/$/,''):null; if(url.protocol!=='https:'||!allowedHosts().has(host)) return null; return url.toString().replace(/\/$/,'');}catch{return null;} }
export async function callLlm({message,history,apiKey,baseUrl,model,fetchImpl=fetch}){ const url=validateProviderUrl(baseUrl); if(!url) throw new Error('LLM_BASE_URL ist ungültig oder nicht freigegeben.'); const cleanModel=String(model||'').trim().slice(0,200); if(!cleanModel) throw new Error('LLM_MODEL fehlt.'); if(!String(apiKey||'').trim()) throw new Error('LLM_API_KEY fehlt.'); const safeHistory=Array.isArray(history)?history.slice(-8).map(e=>({role:e.role==='assistant'?'assistant':'user',content:String(e.content??'').slice(0,4000)})):[]; const r=await fetchImpl(`${url}/chat/completions`,{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:cleanModel,messages:[{role:'system',content:PROJECT_CONTEXT},...safeHistory,{role:'user',content:String(message).slice(0,8000)}],temperature:0.3,max_tokens:1600})}); if(!r.ok) throw new Error(`LLM-Provider ${r.status}: ${(await r.text()).slice(0,500)}`); const data=await r.json(); return data?.choices?.[0]?.message?.content?.trim()||'Der Provider lieferte keine nutzbare Antwort.'; }
export async function createGitHubIssue(mutation,options={}){ const token=options.token??process.env.GITHUB_TOKEN, repository=options.repository??process.env.GITHUB_REPOSITORY??'Pagebabe/comic', fetchImpl=options.fetchImpl??fetch; if(!token) throw new Error('GITHUB_TOKEN fehlt.'); if(repository!=='Pagebabe/comic') throw new Error('Schreibaktionen sind ausschließlich für Pagebabe/comic erlaubt.'); const r=await fetchImpl(`https://api.github.com/repos/${repository}/issues`,{method:'POST',headers:{accept:'application/vnd.github+json',authorization:`Bearer ${token}`,'content-type':'application/json','x-github-api-version':'2022-11-28'},body:JSON.stringify(mutation)}); if(!r.ok) throw new Error(`GitHub ${r.status}: ${(await r.text()).slice(0,500)}`); return r.json(); }

export default async function handler(request,response){ if(request.method!=='POST') return sendJson(response,405,{reply:'Nur POST ist erlaubt.'}); let body; try{body=parseBody(request.body);}catch{return sendJson(response,400,{reply:'Ungültiges JSON.'});} const message=String(body?.message??'').trim().slice(0,8000); if(!message) return sendJson(response,400,{reply:'Nachricht fehlt.'}); const accessRequired=process.env.COMIC_ACCESS_KEY,suppliedAccess=getHeader(request,'x-comic-access-key'); if(accessRequired&&!safeEqual(String(suppliedAccess||''),accessRequired)) return sendJson(response,401,{reply:'Zugriff blockiert: Comic-Zugangsschlüssel fehlt oder ist falsch.'}); const command=message.startsWith('/')?commandReply(message):null; if(command?.mutation){ const expectedAdmin=process.env.COMIC_ADMIN_KEY,suppliedAdmin=getHeader(request,'x-comic-admin-key'); if(!expectedAdmin||!safeEqual(String(suppliedAdmin||''),expectedAdmin)) return sendJson(response,403,{reply:`${command.reply}\nSchreibaktion blockiert: gültiger Admin-Schlüssel fehlt.`}); try{const issue=await createGitHubIssue(command.mutation); return sendJson(response,200,{reply:`${command.reply}\nGitHub-Issue #${issue.number} wurde angelegt.`,issueUrl:issue.html_url});}catch(error){return sendJson(response,502,{reply:`${command.reply}\nGitHub-Schreibfehler: ${error.message}`});} } if(command) return sendJson(response,200,command); const apiKey=getHeader(request,'x-llm-api-key')||process.env.LLM_API_KEY,baseUrl=getHeader(request,'x-llm-base-url')||process.env.LLM_BASE_URL,model=getHeader(request,'x-llm-model')||process.env.LLM_MODEL; if(!apiKey||!baseUrl||!model) return sendJson(response,503,{reply:'LLM noch nicht konfiguriert. Die festen LR5.1-Befehle funktionieren bereits.'}); try{return sendJson(response,200,{reply:await callLlm({message,history:body?.history,apiKey,baseUrl,model})});}catch(error){return sendJson(response,502,{reply:`LLM-Fehler: ${error.message}`});} }
